
# Syntax highlighting
markdown:            kramdown
highlighter:         rouge

# Permalinks
permalink:           pretty
# relative_permalinks: true

# Setup
timezone:            your timezone # eg. Asia/Kathmandu
locale:              your locale language # eg. en_us
name:		     MrCruesliPants
title:               Home Port
tagline:             MrCruesliPants' blog.
description:         A blog about games and stories of any kind.

url:                 http://mrcrueslipants.github.io
baseurl:             /blog
baseurl_posts_img:   '/blog/assets/images/posts/'
baseurl_featured_img: '/blog/assets/images/hero/'
baseurl_featured_thumbnail: '/blog/assets/images/thumbnail/'
baseurl_javascripts: '/blog/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              home-port

rss:                 rss feed url

author:
  name:              MrCruesliPants
      
  twitter:           MrCruesliPants


# Server
# destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml", "org/_posts", "org/_drafts"]
port:             	 9001

gems: [jekyll-sitemap]

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"

